service:

	mariadb:
		container_name: mariadb
		build: ./requirements/mariadb
		image: mariadb:10.11.11
		restart: always
		env_file: .env
		ports:
			- "3306:3306"
		volumes:
			- mariadb:/var/lib/mysql
		networks:
			- networks
		healthcheck:
			test["CMD", "mariadb-admin", "ping", "--protocol=tcp", "--host=localhost", "-u", "$WORDPRESS_DATABASE_USER", "--password=$WORDPRESS_DATABASE_USER_PASSWORD"]
			interval: 10s
			timeour: 5s
			retries: 5


	worldpress:
		container_name:
	eginx:


volumes:
	mariadb:
		name: mariadb
		drive: local

networks: